### ISSUE TITLE
[BUG] AmazonSecurityTokenServiceConfig as ClientConfig return null

### ISSUE THREAD

**Issue by ZLVincent** [opensearch-project/opensearch-net#229]
### What is the bug?
Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.

### How can one reproduce the bug?
```csharp
var endpoint = new Uri(url);
var credentials = new AssumeRoleAWSCredentials(
                                FallbackCredentialsFactory.GetCredentials(),
                                osRole,
                                "Test-OpenSearch");
var osConnn = new AwsSigV4HttpConnection(credentials);
var osConfig = new ConnectionSettings(endpoint, osConnn)
                    .DefaultIndex(index)
                    .EnableHttpCompression(); ;
var osClient = new OpenSearchClient(osConfig);
var countResp = await osClient.CountAsync<CountResponse>(s => s.Query(q => xxx));
```

### What is your host/environment?
AWSSDK.SecurityToken 3.7.103.14
OpenSearch.Net.Auth.AwsSigV4 1.3.0
OpenSearch.Client 1.3.0

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-net/assets/8155380/c4d6a41d-e7ed-4677-abbf-41e34cc2d69e)

### Do you have any additional context?
"Object reference not set to an instance of an object." This exception is because the following code returns null.
In ServiceClientHelpers calss of AWSSDK.Core.dll:
```csharp
public static ClientConfig CreateServiceConfig(string assemblyName, string serviceConfigClassName)
{
    var typeInfo = LoadServiceConfigType(assemblyName, serviceConfigClassName);

    var ci = typeInfo.GetConstructor(new ITypeInfo[0]);
    var config = ci.Invoke(new object[0]);

    return config as ClientConfig;
}
```
It is guessed that it is a problem with the version of the nuget package, which causes the result of the as conversion to be null.
Has anyone else encountered this?

**Comment by Xtansia** [comment]
Hi @ZLVincent,

This does look like a dependency version mismatch between `AWSSDK.Core` and `AWSSDK.SecurityToken`, however usually the higher version requirement of `AWSSDK.Core` from `AWSSDK.SecurityToken` would override the older referenced version from `OpenSearch.Net.Auth.AwsSigV4`.

Could you please run the following command in your project and respond with the output: `dotnet list package --include-transitive`

Additionally, I'd ensure you've attempted a complete clean, restore & build flow to ensure this isn't due to some cached build output.

**Comment by ZLVincent** [comment]
> 

![image](https://github.com/opensearch-project/opensearch-net/assets/8155380/65e48ee1-3653-4b96-aa6e-dcac08b32f5f)

**Comment by Xtansia** [comment]
@ZLVincent Based on that, it does appear dotnet is bringing in the correct version of `AWSSDK.Core` and I am unable to reproduce this error myself with this combination of versions.

Is `GuardianEye.DataSourceEngine.OpenSearch` the actual executable or is it a library project referenced by another project? In which case it's possible the actual executable project is bringing in an older `AWSSDK.*` package and so I'd recommend checking there.

Otherwise the only other possibility I can think of is a stale build output containing an older version of the package.

**Comment by ZLVincent** [comment]
> 

This library is indeed referenced by another project, but I can assure that the actual executable project does not pull in the older AWSSDK.* packages. Actually，When I try to debug, the **serviceConfig** is null, but I execute `**var temp = serviceConfigObj as ClientConfig;**` in the Immediate window of VS2022, and the **temp** is not null, which is really strange.
![image](https://github.com/opensearch-project/opensearch-net/assets/8155380/bf980502-837f-4b85-88e3-54b494047afa)

**Comment by ZLVincent** [comment]
Finnally, I found a way to slove this issue. Because OpenSearch.Net.Auth.AwsSigV4 references the AWSSDK.Core package, I must explicitly reference the AWSSDK.Core package in my library project and add attributes to it: `<ExcludeAssets>runtime</ExcludeAssets>`.
![image](https://github.com/opensearch-project/opensearch-net/assets/8155380/b9f9fc04-fc69-4eda-8167-71485a387de6)

in this way, the AWSSDK.Core.dll file will not exist in the generated dll file. At the same time, reference the AWSSDK.Core and AWSSDK.SecurityToken packages in my main project. Then the AWSSDK.SecurityToken will be loaded with the following code:
`Assembly.Load(new AssemblyName(assemblyName))`

Seems to be working fine so far. I load the library in the form of a plug-in. Maybe my situation is special, so I have this problem. Anyway, I would like to thank you for your help.
Finally, can I ask why the AWSSDK.SecurityToken is loaded in the way of dynamically loading the DLL instead of other ways?

**Comment by Xtansia** [comment]
> Finally, can I ask why the AWSSDK.SecurityToken is loaded in the way of dynamically loading the DLL instead of other ways?

That is part of AWSSDK.Core, not anything related to OpenSearch.Net.Auth.AwsSigV4, so I can not say for sure.

**Comment by ZLVincent** [comment]
> > Finally, can I ask why the AWSSDK.SecurityToken is loaded in the way of dynamically loading the DLL instead of other ways?
> 
> That is part of AWSSDK.Core, not anything related to OpenSearch.Net.Auth.AwsSigV4, so I can not say for sure.

Understood, thank you very much for your reply
