### ISSUE TITLE
[FEATURE] Add support for inclusive naming

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/opensearch-net#89]
Add support for inclusive naming by deprecating the master nomenclature.

See meta issue https://github.com/opensearch-project/opensearch-clients/issues/16 for details.

**Comment by Yury-Fridlyand** [comment]
@wbeckler,
This is already done in scope of #51.
* All `master` references replaced by `cluster_manager`
except
`master` references in API (it is marked as obsolete, but not removed yet) and in comments to these API:
  * `master` node renamed to `cluster_manager` (actually duplicated for BWC with OpenSearch 1.x)
  * `master_timeout` field renamed to `cluster_manager_timeout` (duplicated too)
  * `masterEligible` duplicated by `clusterManagerEligible` (not an OpenSearch API, but might be in use by customer applications)
* Fortunately, no `blacklist`/`whitelist` references in the client code/API, nothing to do there.

Please, check if something is missed and report here. Otherwise we can close this ticket once #51 merged.

**Comment by harshavamsi** [comment]
@wbeckler @Yury-Fridlyand can we close this?
